# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASEIMAGE
FROM claudiubelu/windows-image-builder-helper:1.0 as helper

RUN powershell -Command "curl.exe -L 'https://openresty.org/download/openresty-1.13.6.2-win64.zip' -o 'C:\openresty-1.13.6.2-win64.zip'; \
    Expand-Archive -Path C:\openresty-1.13.6.2-win64.zip -DestinationPath C:\openresty -Force; \
    Remove-Item 'C:\openresty-1.13.6.2-win64.zip'"
RUN choco install openssl.light -y

FROM $BASEIMAGE

COPY --from=helper /openresty /openresty
COPY --from=helper /Windows/System32/vcruntime140.dll /Windows/System32/
COPY --from=helper ["C:/Program Files/OpenSSL", "C:/Program Files/"]

USER ContainerAdministrator
RUN setx /M PATH "C:\openresty\openresty-1.13.6.2-win64\;%PATH%"
USER ContainerUser

ADD run.sh /openresty/openresty-1.13.6.2-win64/run.sh
ADD nginx_windows.conf /openresty/openresty-1.13.6.2-win64/conf/nginx.conf
ADD template.lua /openresty/openresty-1.13.6.2-win64/lua/template.lua

EXPOSE 80 443 8080 8443
ENTRYPOINT ["/bin/sh", "/openresty/openresty-1.13.6.2-win64/run.sh"]
