# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASEIMAGE
FROM claudiubelu/windows-image-builder-helper:1.0 as helper
FROM $BASEIMAGE

COPY --from=helper /Windows/System32/netapi32.dll /Windows/System32/netapi32.dll

USER ContainerAdministrator
RUN mkdir C:\build\nginx\source &&\
    curl -L http://nginx.org/download/nginx-1.15.12.zip -o nginx.zip &\
    powershell -Command "Expand-Archive -Path C:\nginx.zip -DestinationPath C:\nginx -Force" &&\
    del C:\nginx.zip
RUN mkdir C:\usr\share &&\
    mklink /D C:\usr\share\nginx C:\nginx\nginx-1.15.12 &&\
    mklink C:\Windows\System32\sync.exe C:\Windows\System32\SyncHost.exe
WORKDIR /nginx/nginx-1.15.12
EXPOSE 80
ENTRYPOINT ["nginx.exe"]
